# -*- coding: utf-8 -*-
"""Arima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpPBYx4gimXZhlUH0hjjkoQYsVZVxe6s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/perrin-freres-monthly-champagne-.csv")

df.head()

df.tail()

#cleaning up the data
df.columns=["Month","Sales"]
df.head()

df.drop(106,axis=0,inplace=True)

df.tail()

df.tail()

df.drop(105,axis=0,inplace=True)

#covert month to datetime
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month',inplace=True)

df.describe()

df.info()

#visualize the data
df.plot()

from statsmodels.tsa.stattools import adfuller
test_result = adfuller(df["Sales"])

def adfuller_test(sales):
    result=adfuller(sales)
    labels = ['ADF Test Statistic','p-value','#Lags Used','Number of Observations Used']
    for value,label in zip(result,labels):
        print(label+' : '+str(value) )
    if result[1] <= 0.05:
        print("strong evidence against the null hypothesis(Ho), reject the null hypothesis. Data has no unit root and is stationary")
    else:
        print("weak evidence against null hypothesis, time series has a unit root, indicating it is non-stationary ")

adfuller_test(df['Sales'])

#differencing
df['Sales First Difference']= df['Sales']-df['Sales'].shift(1) #seasonal shift

df.head(14)

#differencing
df['Seasonal First Difference']= df['Sales']-df['Sales'].shift(12) #seasonal shift

adfuller_test(df['Seasonal First Difference'].dropna())

df['Seasonal First Difference'].plot()

#Auto regressive model
from pandas.plotting import autocorrelation_plot
autocorrelation_plot(df['Sales'])
plt.show()

from statsmodels.graphics.tsaplots import plot_acf,plot_pacf

import statsmodels.api as sm
fig = plt.figure(figsize=(12,8))
ax1 = fig.add_subplot(211)
fig = sm.graphics.tsa.plot_acf(df['Seasonal First Difference'].iloc[13:],lags=40,ax=ax1)
ax2 = fig.add_subplot(212)
fig = sm.graphics.tsa.plot_pacf(df['Seasonal First Difference'].iloc[13:],lags=40,ax=ax2)

# For non-seasonal data
# p=1, d=1, q=0 or 1
from statsmodels.tsa.statespace.sarimax import SARIMAX

model=SARIMAX(df['Sales'],order=(1,1,1))
model_fit=model.fit()

model_fit.summary()

df['forecast']=model_fit.predict(start=90,end=103,dynamic=True)
df[['Sales','forecast']].plot(figsize=(12,8))

import statsmodels.api as sm
model=sm.tsa.statespace.SARIMAX(df['Sales'],order=(1, 1, 1),seasonal_order=(1,1,1,12))
results=model.fit()

df['forecast']=results.predict(start=90,end=103,dynamic=True)
df[['Sales','forecast']].plot(figsize=(12,8))

from pandas.tseries.offsets import DateOffset
future_dates=[df.index[-1]+ DateOffset(months=x)for x in range(0,24)]

future_df=pd.DataFrame(index=future_dates[1:],columns=df.columns)
full_df = pd.concat([df,future_df])
full_df['forecast'] = results.predict(start=len(df),end=len(df)+22,dynamic=True)
full_df[['Sales','forecast']].plot(figsize=(12,8))

