# -*- coding: utf-8 -*-
"""miniproject using lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9JA0Sscd_jeCTnOVOVukjmJDFlKTxGU
"""

import pandas as pd
import numpy as np

data = {    "name": ["Asha", "Ben", "Chitra", "Daniel", "Esha", "Farhan", "Gita", "Hari", "Isha", "John"],
    "age":  [22,    35,   28,      41,       33,    26,      45,    31,    29,    38],
    "salary":[32000,52000,41000,   68000,    59000,36000,   75000, 61000, 43000, 67000]}

data

df=pd.DataFrame(data)
df

csv_path = "employees.csv"
df.to_csv(csv_path, index=False)
print("✅ CSV created:", csv_path)

df_read = pd.read_csv(csv_path)
print("\n--- 1) Read CSV ---")
print(df_read)

students_marks = np.array([56, 60, 75, 72, 90, 95, 88, 92])

mean_marks = np.mean(students_marks)
max_marks = np.max(students_marks)

# (current - previous) / previous * 100
pct_increase = (students_marks[1:] - students_marks[:-1]) / students_marks[:-1] * 100

print("\n--- 2) Students Marks ---")
print("Marks:", students_marks)
print("Mean:", mean_marks)
print("Max:", max_marks)
print("% increase from previous:", np.round(pct_increase, 2))

df_over_30 = df_read[df_read["age"] > 30].copy()

avg_salary_over_30 = df_over_30["salary"].mean()
df_sorted_desc = df_over_30.sort_values(by="salary", ascending=False)

print("\n--- 3) Age > 30 ---")
print(df_over_30)
print("Average salary (age > 30):", round(avg_salary_over_30, 2))

print("\nSorted by salary (desc):")
print(df_sorted_desc)

print("\n--- 4) EDA ---")
print("\nData types:")
print(df_read.dtypes)

print("\nDescribe (numeric summary):")
print(df_read.describe())

print("\nNull values per column:")
print(df_read.isnull().sum())

